# Generated by Django 5.0.4 on 2024-04-19 04:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_job_id', models.CharField(default='', max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.job')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_title', models.CharField(default='', max_length=100, unique=True)),
                ('repo_url', models.CharField(default='', max_length=100)),
                ('repo_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo_updated_at', models.DateTimeField(auto_now=True)),
                ('repo_forks', models.IntegerField(default=0)),
                ('repo_stars', models.IntegerField(default=0)),
                ('repo_img', models.CharField(default='', max_length=100)),
                ('repo_view', models.IntegerField(default=0)),
                ('repo_recent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo_writer', models.CharField(default='', max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs_title', models.CharField(default='', max_length=100, unique=True)),
                ('qs_url', models.CharField(default='', max_length=100)),
                ('qs_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qs_updated_at', models.DateTimeField(auto_now=True)),
                ('qs_view', models.IntegerField(default=0)),
                ('qs_img', models.CharField(default='', max_length=100)),
                ('qs_votes', models.IntegerField(default=0)),
                ('qs_answer', models.CharField(default='', max_length=100)),
                ('qs_writer', models.CharField(default='', max_length=100)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill')),
            ],
        ),
    ]
