# Generated by Django 5.0.4 on 2024-04-17 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.job')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forks', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('img', models.CharField(default='', max_length=100)),
                ('view', models.IntegerField(default=0)),
                ('repo_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repo_tags', models.CharField(default='', max_length=100)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view', models.IntegerField(default=0)),
                ('question_tags', models.CharField(default='', max_length=100)),
                ('img', models.CharField(default='', max_length=100)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill')),
            ],
        ),
    ]
