# Generated by Django 5.0.4 on 2024-04-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicsTrending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qs_title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
