# Generated by Django 5.0.4 on 2024-04-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicsTrending', '0002_job_created_at_job_updated_at_question_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='techBlog',
        ),
        migrations.DeleteModel(
            name='TechBlog',
        ),
    ]
