# Generated by Django 5.0.4 on 2024-04-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicsTrending', '0002_alter_question_qs_title_alter_repository_repo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_img',
            field=models.ImageField(upload_to='img/git/Android/forks/'),
        ),
    ]
