# Generated by Django 5.0.4 on 2024-04-16 11:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicsTrending', '0003_remove_skill_techblog_delete_techblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='question_tags',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='forks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_tags',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.question'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='repository',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.repository'),
        ),
    ]
