# Generated by Django 5.0.4 on 2024-04-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicsTrending', '0005_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.question'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.repository'),
        ),
    ]
