# Generated by Django 5.0.4 on 2024-04-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicsTrending', '0006_alter_job_skill_alter_skill_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.question'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='repository',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.repository'),
        ),
    ]
