# Generated by Django 5.0.4 on 2024-04-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicsTrending', '0007_alter_skill_question_alter_skill_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='question',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='repository',
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill'),
        ),
        migrations.AddField(
            model_name='repository',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TopicsTrending.job'),
        ),
    ]
